import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, CheckCircle2, CircleAlert, Download,
  FileText, Gauge, Landmark, LoaderCircle, Network, RefreshCw, ShieldCheck, Target,
  UploadCloud, WalletCards
} from 'lucide-react';

const API = '/api';
const STORE = 'live-synesis-institutional-lab-v4';
const TYPES = [
  ['portfolio', 'Portfolio intelligence', WalletCards, 'Calculate holdings, concentration, liquidity and redemption sensitivity from an uploaded CSV.'],
  ['mandate', 'Mandate & restrictions', Target, 'Extract limits and test them against the active calculated portfolio.'],
  ['regulatory', 'Regulatory impact', Landmark, 'Run live deep analysis with current-source verification for a regulatory update.'],
  ['scenario', 'Cross-functional simulation', Activity, 'Model an event across capital, liquidity, operations, regulation, governance and stakeholders.']
];
const SCENARIOS = ['regulatory','liquidity','cyber','counterparty','contract','sanctions','litigation','governance','market','operational','generic'];
const FUNCTIONS = ['Investment / Treasury','Risk','Compliance','Legal','Operations','Technology','Finance / Credit','Management','Board / Trustees','Procurement'];

function load() { try { return JSON.parse(localStorage.getItem(STORE) || '{}') || {}; } catch { return {}; } }
function save(value) { localStorage.setItem(STORE, JSON.stringify(value)); }
function riskClass(value='Low') { return `lab-risk ${String(value).toLowerCase()}`; }
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
async function api(path,body){const response=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!response.ok)throw new Error(data.detail||data.error||'LIVE SYNESIS request failed.');return data}
async function extract(file){const ext=file.name.split('.').pop()?.toLowerCase();if(ext==='pdf'){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/legacy/build/pdf.worker.min.mjs',import.meta.url).toString();const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i+=1){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(`PAGE ${i}\n${content.items.map(item=>item.str).join(' ')}`)}return pages.join('\n\n')}if(ext==='docx'){const module=await import('mammoth/mammoth.browser.js');const mammoth=module.default||module;return(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value}return file.text()}

export default function InstitutionalLab(){
  const stored=useMemo(load,[]);
  const [tab,setTab]=useState(stored.tab||'portfolio');
  const [portfolio,setPortfolio]=useState(stored.portfolio||null);
  const [mandate,setMandate]=useState(stored.mandate||null);
  const [regulatory,setRegulatory]=useState(stored.regulatory||null);
  const [simulation,setSimulation]=useState(stored.simulation||null);
  const [notice,setNotice]=useState(null);
  useEffect(()=>save({tab,portfolio,mandate,regulatory,simulation}),[tab,portfolio,mandate,regulatory,simulation]);
  return <div className="lab-shell">
    <section className="lab-hero"><div><small>CONNECTED SOLUTION PACK</small><h1>Capital, mandate, regulation and scenario intelligence</h1><p>Calculations are produced from uploaded data. Document reasoning is live and evidence-led. Simulations disclose their assumptions and do not pretend to be market forecasts.</p></div><Network size={46}/></section>
    {notice&&<button className={`lab-notice ${notice.type}`} onClick={()=>setNotice(null)}>{notice.type==='error'?<CircleAlert size={17}/>:<CheckCircle2 size={17}/>}<span>{notice.message}</span></button>}
    <nav className="lab-tabs">{TYPES.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={18}/>{label}</button>)}</nav>
    {tab==='portfolio'&&<PortfolioTool result={portfolio} setResult={setPortfolio} notify={setNotice}/>} 
    {tab==='mandate'&&<MandateTool portfolio={portfolio} result={mandate} setResult={setMandate} notify={setNotice}/>} 
    {tab==='regulatory'&&<RegulatoryTool result={regulatory} setResult={setRegulatory} notify={setNotice}/>} 
    {tab==='scenario'&&<ScenarioTool context={{portfolio,mandate,regulatory}} result={simulation} setResult={setSimulation} notify={setNotice}/>} 
  </div>
}

function FileInput({accept,onText,title='Upload source'}){const[busy,setBusy]=useState(false);async function choose(file){if(!file)return;setBusy(true);try{onText(await extract(file),file)}catch(error){onText('',file,error)}finally{setBusy(false)}}return <label className="lab-drop"><input type="file" accept={accept} onChange={event=>choose(event.target.files?.[0])}/>{busy?<LoaderCircle className="spin" size={25}/>:<UploadCloud size={25}/>}<strong>{busy?'Reading source…':title}</strong><small>{accept}</small></label>}
function ResultHeader({title,result}){return <div className="lab-result-head"><div><small>ACTIVE RESULT</small><h2>{title}</h2></div>{result?.overall_risk&&<span className={riskClass(result.overall_risk)}>{result.overall_risk} {Number.isFinite(result.overall_score)?`${result.overall_score}/100`:''}</span>}<button onClick={()=>download(`${title}.json`,JSON.stringify(result,null,2))}><Download size={15}/>JSON</button></div>}
function Empty({text}){return <div className="lab-empty"><FileText size={25}/><p>{text}</p></div>}

function PortfolioTool({result,setResult,notify}){
  const[text,setText]=useState('');const[title,setTitle]=useState('Portfolio upload');const[busy,setBusy]=useState(false);
  async function run(){if(text.trim().length<20)return notify({type:'error',message:'Upload or paste a portfolio CSV.'});setBusy(true);try{const data=await api('/public/institutional/portfolio',{text,title,currency:'As supplied'});setResult(data.analysis);notify({type:'success',message:'Portfolio calculated from the uploaded rows.'})}catch(error){notify({type:'error',message:error.message})}finally{setBusy(false)}}
  return <div className="lab-grid"><section className="lab-card"><h2>Calculate the portfolio</h2><p>Expected columns may include security, issuer, sector, asset class, market value or weight, rating and liquidity days.</p><FileInput accept=".csv,.txt" title="Upload portfolio CSV" onText={(value,file,error)=>{if(error)return notify({type:'error',message:error.message});setText(value);setTitle(file.name.replace(/\.[^.]+$/,''))}}/><textarea rows="10" value={text} onChange={event=>setText(event.target.value)} placeholder="Paste portfolio CSV…"/><button className="lab-primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<BarChart3 size={17}/>}Calculate exposures</button></section><section className="lab-card">{result?<PortfolioResult result={result}/>:<Empty text="Upload a real portfolio to calculate exposures and redemption sensitivity."/>}</section></div>
}
function PortfolioResult({result}){const metrics=result.metrics||{};return <><ResultHeader title={result.title||'Portfolio intelligence'} result={result}/><div className="lab-metrics">{Object.entries(metrics).slice(0,8).map(([key,value])=><div key={key}><strong>{value}</strong><small>{key.replaceAll('_',' ')}</small></div>)}</div><h3>Concentration and control flags</h3><div className="lab-list">{(result.flags||[]).map((item,index)=><article key={item.id||index}><span className={riskClass(item.severity)}>{item.severity}</span><div><strong>{item.title}</strong><p>{item.evidence}</p><small>{item.action}</small></div></article>)}</div><h3>Redemption sensitivity</h3><div className="lab-scenarios">{(result.redemption_scenarios||[]).map((item,index)=><article key={index}><strong>{item.redemption_percent}% redemption</strong><span>{item.executable?'Executable':'Constraint identified'}</span><p>Slow-asset sales: {item.estimated_slow_asset_sales_percent}%</p><small>Uncovered: {item.uncovered_percent}%</small></article>)}</div>{(result.data_gaps||[]).length>0&&<><h3>Data gaps</h3><ul>{result.data_gaps.map((item,index)=><li key={index}>{item}</li>)}</ul></>}</>}

function MandateTool({portfolio,result,setResult,notify}){
  const[text,setText]=useState('');const[title,setTitle]=useState('Mandate compliance review');const[busy,setBusy]=useState(false);
  async function run(){if(text.trim().length<20)return notify({type:'error',message:'Upload or paste the scheme mandate or investment restrictions.'});setBusy(true);try{const data=await api('/public/institutional/mandate',{text,title,portfolio});setResult(data.analysis);notify({type:'success',message:portfolio?'Mandate mapped and tested against the active portfolio.':'Mandate extracted; upload a portfolio for calculated testing.'})}catch(error){notify({type:'error',message:error.message})}finally{setBusy(false)}}
  return <div className="lab-grid"><section className="lab-card"><h2>Map mandate and restrictions</h2><p>{portfolio?'The active portfolio will be tested against extracted quantitative limits.':'No active portfolio is linked. Synesis will extract restrictions but cannot calculate compliance.'}</p><FileInput accept=".pdf,.docx,.txt,.md" title="Upload mandate or scheme document" onText={(value,file,error)=>{if(error)return notify({type:'error',message:error.message});setText(value);setTitle(file.name.replace(/\.[^.]+$/,''))}}/><textarea rows="10" value={text} onChange={event=>setText(event.target.value)} placeholder="Paste mandate, scheme information or restriction text…"/><button className="lab-primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Target size={17}/>}Map and test mandate</button></section><section className="lab-card">{result?<><ResultHeader title={result.title||title} result={{overall_risk:result.breach_count?'High':'Low',overall_score:result.breach_count?80:20}}/><div className="lab-metrics"><div><strong>{result.restrictions?.length||0}</strong><small>restrictions</small></div><div><strong>{result.breach_count||0}</strong><small>breaches</small></div><div><strong>{result.warning_count||0}</strong><small>warnings</small></div></div><div className="lab-list">{(result.tests||result.restrictions||[]).map((item,index)=><article key={item.id||index}><span className={riskClass(item.status==='Breach'?'High':item.status==='Warning'?'Medium':'Low')}>{item.status||'Extracted'}</span><div><strong>{item.label||item.restriction||item.rule}</strong><p>{item.explanation||item.evidence||item.reference}</p><small>{item.action||item.status}</small></div></article>)}</div></>:<Empty text="Upload a mandate. Link a calculated portfolio to test limits, not merely extract text."/>}</section></div>
}

function RegulatoryTool({result,setResult,notify}){
  const[text,setText]=useState('');const[title,setTitle]=useState('Regulatory change assessment');const[busy,setBusy]=useState(false);
  async function run(){if(text.trim().length<20)return notify({type:'error',message:'Upload or paste the regulatory source.'});setBusy(true);try{const data=await api('/public/analyze',{text,title,matter:'Regulatory change assessment',documentType:'Regulatory / Policy Document',jurisdiction:'India',riskAppetite:'Conservative',department:'Compliance',workType:'Assess a regulatory change',stakeholderLens:'Institution, regulators, customers/investors and affected operations',analysisMode:'deep',useCurrentSources:true,countryCode:'IN',city:'New Delhi',region:'Delhi',timezone:'Asia/Kolkata'});setResult(data.analysis);notify({type:data.analysis.analysis_details?.live_ai_used?'success':'error',message:data.analysis.analysis_details?.live_ai_used?'Live regulatory analysis and decision model completed.':'Live AI failed; result is only an emergency fallback.'})}catch(error){notify({type:'error',message:error.message})}finally{setBusy(false)}}
  return <div className="lab-grid"><section className="lab-card"><h2>Assess regulatory change</h2><p>Deep analysis identifies applicability, affected obligations, controls, owners, approval gates and closure evidence. Current-source verification is requested separately.</p><FileInput accept=".pdf,.docx,.txt,.md,.xml" title="Upload circular, direction or policy" onText={(value,file,error)=>{if(error)return notify({type:'error',message:error.message});setText(value);setTitle(file.name.replace(/\.[^.]+$/,''))}}/><textarea rows="10" value={text} onChange={event=>setText(event.target.value)} placeholder="Paste the regulatory source…"/><button className="lab-primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Landmark size={17}/>}Run deep regulatory assessment</button></section><section className="lab-card">{result?<RegulatoryResult result={result}/>:<Empty text="Upload the actual regulatory source. Synesis will separate document evidence from current-source verification."/>}</section></div>
}
function RegulatoryResult({result}){const decision=result.decision_intelligence||{};return <><ResultHeader title={result.document_title||'Regulatory assessment'} result={result}/>{!result.analysis_details?.live_ai_used&&<div className="lab-warning"><CircleAlert size={18}/><span>Emergency fallback only. Do not rely on this as completed analysis.</span></div>}<p className="lab-long">{result.executive_position}</p><h3>Decisions required</h3><ol>{(decision.decision_questions||[]).map((item,index)=><li key={index}>{item}</li>)}</ol><h3>Controlled action plan</h3><div className="lab-list">{(decision.action_plan||[]).map((item,index)=><article key={index}><span className="lab-risk medium">{item.priority}</span><div><strong>{item.action}</strong><p>Owner: {item.owner}</p><small>Gate: {item.approval_gate} · Evidence: {item.completion_evidence}</small></div></article>)}</div><h3>Verified current sources</h3><p className="lab-long">{result.source_verification?.summary||'Current-source verification was not returned.'}</p>{(result.source_verification?.sources||[]).map((item,index)=><a className="lab-source" key={index} href={item.url} target="_blank" rel="noreferrer">{item.title}<ArrowRight size={14}/></a>)}</>}

function ScenarioTool({context,result,setResult,notify}){
  const[form,setForm]=useState({title:'Institutional stress event',scenarioType:'generic',trigger:'',probability:3,severity:3,speed:3,durationDays:30,controlStrength:2,financialExposure:0,affectedFunctions:['Risk','Compliance','Legal','Operations','Management'],controls:[]});const[busy,setBusy]=useState(false);
  async function run(){setBusy(true);try{const data=await api('/public/institutional/simulate',{...form,context});setResult(data.analysis);notify({type:'success',message:'Scenario calculated from the supplied assumptions and linked context.'})}catch(error){notify({type:'error',message:error.message})}finally{setBusy(false)}}
  function toggle(fn){setForm(current=>({...current,affectedFunctions:current.affectedFunctions.includes(fn)?current.affectedFunctions.filter(item=>item!==fn):[...current.affectedFunctions,fn]}))}
  return <div className="lab-grid"><section className="lab-card"><h2>Run cross-functional simulation</h2><p>This is a sensitivity and governance model—not a market forecast. Supply facts, exposure and controls; Synesis will show assumptions and evidence gaps.</p><div className="lab-fields"><label>Title<input value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label>Scenario<select value={form.scenarioType} onChange={event=>setForm({...form,scenarioType:event.target.value})}>{SCENARIOS.map(item=><option key={item}>{item}</option>)}</select></label><label className="wide">Factual trigger<textarea rows="4" value={form.trigger} onChange={event=>setForm({...form,trigger:event.target.value})} placeholder="Describe what has happened or may happen…"/></label>{[['Probability', 'probability'],['Severity','severity'],['Speed','speed'],['Control strength','controlStrength']].map(([label,key])=><label key={key}>{label}: {form[key]}<input type="range" min={key==='controlStrength'?0:1} max="5" value={form[key]} onChange={event=>setForm({...form,[key]:Number(event.target.value)})}/></label>)}<label>Duration (days)<input type="number" min="1" value={form.durationDays} onChange={event=>setForm({...form,durationDays:Number(event.target.value)})}/></label><label>Financial exposure<input type="number" min="0" value={form.financialExposure} onChange={event=>setForm({...form,financialExposure:Number(event.target.value)})}/></label><div className="wide"><small>Affected functions</small><div className="lab-functions">{FUNCTIONS.map(item=><button type="button" key={item} className={form.affectedFunctions.includes(item)?'active':''} onClick={()=>toggle(item)}>{item}</button>)}</div></div></div><button className="lab-primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Gauge size={17}/>}Calculate scenario</button></section><section className="lab-card">{result?<ScenarioResult result={result}/>:<Empty text="Configure an event. Active portfolio, mandate and regulatory context will be linked automatically when available."/>}</section></div>
}
function ScenarioResult({result}){return <><ResultHeader title={result.title||result.scenario_label||'Institutional simulation'} result={{overall_risk:result.level||result.overall_risk,overall_score:result.overall_score}}/><p className="lab-long">{result.executive_summary||result.summary}</p><h3>Scenario variants</h3><div className="lab-scenarios">{(result.variants||[]).map((item,index)=><article key={index}><strong>{item.name}</strong><span className={riskClass(item.level)}>{item.level} · {item.overall_score}</span><p>Time to critical: {item.time_to_critical_hours}h</p><small>{item.exposure_basis}</small></article>)}</div><h3>Cascade</h3><div className="lab-list">{(result.cascade||[]).map((item,index)=><article key={item.id||index}><span className="lab-step">{item.sequence}</span><div><strong>{item.event}</strong><p>{item.state} · starts around {item.estimated_start_hours}h</p><small>Owner: {item.owner}</small></div></article>)}</div><h3>Approval-gated actions</h3><div className="lab-list">{(result.actions||[]).map((item,index)=><article key={item.id||index}><span className="lab-risk medium">{item.priority}</span><div><strong>{item.action}</strong><p>Owner: {item.owner}</p><small>Gate: {item.approval_gate} · Evidence: {item.completion_evidence}</small></div></article>)}</div>{(result.evidence_gaps||[]).length>0&&<><h3>Evidence gaps</h3><ul>{result.evidence_gaps.map((item,index)=><li key={index}>{item}</li>)}</ul></>}</>}
