import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Archive, ArrowRight, BarChart3, BellRing, Bot, BrainCircuit,
  Building2, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Database, FileCheck2,
  FilePlus2, FileSearch2, FileText, Fingerprint, Gauge, GitBranch, Globe2, KeyRound,
  LayoutDashboard, LibraryBig, Link2, ListChecks, LogOut, Menu, MessageSquareText,
  Network, Play, Plus, RefreshCw, Scale, Search, Send, Settings2, ShieldCheck, Sparkles,
  Target, UploadCloud, UserCog, Users, X, Zap
} from 'lucide-react';
import { formatDate, money, downloadJson, tone, Modal, Panel, RiskBadge, Status, KeyValue, MiniProgress, ProgressRow } from './ui.jsx';

export function Impact({ state, request, setState, setNotice }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: '', source: '', effectiveDate: '', severity: 'High' });
  async function submit(e) { e.preventDefault(); try { const data = await request('/regulatory-change', { method: 'POST', body: JSON.stringify(form) }); setState(data.state); setOpen(false); setNotice({ type: 'success', message: 'Change registered for source verification and impact assessment.' }); } catch (err) { setNotice({ type: 'error', message: err.message }); } }
  return <><div className="page-intro"><div><span className="eyebrow">REGULATORY IMPACT GRAPH</span><h2>See the institutional blast radius before the deadline.</h2><p>Every verified change is traced to documents, controls, products, vendors, systems, teams and unresolved decisions.</p></div><button className="primary" onClick={() => setOpen(true)}><Plus size={17} /> Register change</button></div><div className="impact-list">{state.impacts.map(item => <article key={item.id}><div className="impact-main"><RiskBadge value={item.severity} /><div><h3>{item.title}</h3><p>{item.source} · Effective {formatDate(item.effectiveDate)} · {item.confidence}% confidence</p></div><Status value={item.status} /></div><div className="blast-grid">{Object.entries(item.affected || {}).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{key}</span></div>)}</div><div className="impact-path"><span>Source verified</span><ChevronRight /><span>Impact mapped</span><ChevronRight /><span>Owners assigned</span><ChevronRight /><span>Evidence pending</span></div></article>)}</div>{open && <Modal title="Register a controlled source change" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={submit}><label className="full">Change title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} required /></label><label>Source<input value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} /></label><label>Effective date<input type="date" value={form.effectiveDate} onChange={e => setForm({ ...form, effectiveDate: e.target.value })} /></label><label>Severity<select value={form.severity} onChange={e => setForm({ ...form, severity: e.target.value })}>{['Critical', 'High', 'Medium', 'Low'].map(x => <option key={x}>{x}</option>)}</select></label><div className="full form-actions"><button type="button" className="ghost" onClick={() => setOpen(false)}>Cancel</button><button className="primary">Register and assess</button></div></form></Modal>}</>;
}

export function Obligations({ state }) {
  const [query, setQuery] = useState('');
  const items = state.obligations.filter(item => JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));
  return <><div className="toolbar"><div className="search-box wide"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search obligation, source, owner or control" /></div><span className="counter">{items.length} active obligations</span></div><div className="table-card"><table><thead><tr><th>Obligation</th><th>Source / reference</th><th>Owner</th><th>Deadline</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><div className="cell-title"><RiskBadge value={item.risk} /><span><strong>{item.title}</strong><small>{item.type} · {(item.controls || []).join(', ')}</small></span></div></td><td><strong>{item.source}</strong><small>{item.sourceRef}</small></td><td>{item.owner}</td><td>{formatDate(item.due)}</td><td><Status value={item.status} /></td><td><MiniProgress value={item.evidence} /></td></tr>)}</tbody></table></div><div className="two-col"><Panel title="Control effectiveness" subtitle="Assurance measured against linked obligations">{state.controls.map(control => <ProgressRow key={control.id} label={`${control.id} · ${control.name}`} value={control.effectiveness} meta={`${control.owner} · ${control.linkedObligations} linked obligations`} />)}</Panel><Panel title="Obligation compiler" subtitle="What the engine produces"><div className="compiler-grid">{['Requirement', 'Permission', 'Prohibition', 'Trigger', 'Deadline', 'Threshold', 'Owner', 'Control', 'Approval gate', 'Completion evidence'].map(item => <span key={item}><CheckCircle2 />{item}</span>)}</div></Panel></div></>;
}

export function Decisions({ state, request, setState, setNotice }) {
  const [selected, setSelected] = useState(null);
  const [approvalNote, setApprovalNote] = useState('');
  async function update(decision, status) { try { const data = await request(`/decisions/${decision.id}`, { method: 'PATCH', body: JSON.stringify({ status, approvalNote }) }); setState(data.state); setSelected(null); setApprovalNote(''); setNotice({ type: 'success', message: `${decision.title}: ${status}` }); } catch (err) { setNotice({ type: 'error', message: err.message }); } }
  return <><div className="decision-list">{state.decisions.map(item => <article key={item.id}><div className="decision-top"><RiskBadge value={item.risk} /><Status value={item.status} /><span>Due {formatDate(item.due)}</span></div><h3>{item.title}</h3><p>{item.matter}</p><div className="rationale"><small>Current rationale</small>{item.rationale}</div><div className="approval-line">{(item.approvals || []).map((approval, index) => <div key={index}><span className={`approval-dot ${tone(approval.status)}`} />{approval.role}<small>{approval.status}</small></div>)}</div><footer><span>Accountable owner: <strong>{item.owner}</strong></span><button className="primary" onClick={() => setSelected(item)}>Open decision <ChevronRight size={16} /></button></footer></article>)}</div>{selected && <Modal title={selected.title} onClose={() => setSelected(null)}><div className="decision-modal"><RiskBadge value={selected.risk} /><p>{selected.rationale}</p><label>Approval / challenge note<textarea value={approvalNote} onChange={e => setApprovalNote(e.target.value)} placeholder="Record the evidence, assumptions, controls and accountable reasoning. Critical approvals require a substantive note." /></label><div className="decision-actions"><button className="danger" onClick={() => update(selected, 'Rejected')}>Reject</button><button className="ghost" onClick={() => update(selected, 'Challenge')}>Challenge</button><button className="ghost" onClick={() => update(selected, 'Approved with controls')}>Approve with controls</button><button className="primary" onClick={() => update(selected, 'Approved')}>Approve</button></div></div></Modal>}</>;
}

export function Execution({ state, request, setState, setNotice }) {
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  const [form, setForm] = useState({ title: '', entity: '', note: '' });
  async function submit(e) { e.preventDefault(); try { const data = await request('/evidence', { method: 'POST', body: JSON.stringify(form) }); setState(data.state); setEvidenceOpen(false); setForm({ title: '', entity: '', note: '' }); setNotice({ type: 'success', message: 'Evidence added to the verification queue.' }); } catch (err) { setNotice({ type: 'error', message: err.message }); } }
  async function verify(item, status) { try { const note = status === 'Rejected' ? window.prompt('Reason for rejection') || '' : 'Verified against the linked obligation and completion criteria.'; const data = await request(`/evidence/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status, note }) }); setState(data.state); setNotice({ type: 'success', message: `${item.title}: ${status}` }); } catch (err) { setNotice({ type: 'error', message: err.message }); } }
  return <><div className="page-intro"><div><span className="eyebrow">GOVERNED EXECUTION ENGINE</span><h2>Approval is not completion.</h2><p>Synesis follows the approved response through dependencies, blockers, evidence verification, exception handling and closure.</p></div><button className="primary" onClick={() => setEvidenceOpen(true)}><Plus size={17} /> Add evidence</button></div><div className="two-col wide-left"><Panel title="Execution pulse" subtitle="Actions by current state"><div className="execution-bars">{['Not started', 'Ready', 'In progress', 'Blocked', 'Evidence review', 'Completed'].map(status => { const count = state.tasks.filter(item => item.status === status).length; return <div key={status}><span>{status}</span><div><i style={{ width: `${Math.max(4, count * 18)}%` }} /></div><strong>{count}</strong></div>; })}</div></Panel><Panel title="Evidence assurance" subtitle={`${state.metrics.evidenceCoverage}% verified`}><div className="donut" style={{ '--value': state.metrics.evidenceCoverage }}><strong>{state.metrics.evidenceCoverage}%</strong><span>coverage</span></div></Panel></div><div className="section-head"><div><small>Evidence register</small><h2>Proof of completion</h2></div></div><div className="evidence-grid">{state.evidence.map(item => <div className="evidence-card" key={item.id}><FileCheck2 /><div><strong>{item.title}</strong><p>{item.entity} · {formatDate(item.date)}</p><Status value={item.status} />{item.verificationNote && <p>{item.verificationNote}</p>}</div><div><span>{item.verifiedBy || 'Awaiting verifier'}</span>{item.status === 'Pending verification' && <div className="evidence-actions"><button className="text-button" onClick={() => verify(item, 'Verified')}>Verify</button><button className="text-button" onClick={() => verify(item, 'Rejected')}>Reject</button></div>}</div></div>)}</div>{evidenceOpen && <Modal title="Add completion evidence" onClose={() => setEvidenceOpen(false)}><form className="form-grid" onSubmit={submit}><label className="full">Evidence title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label className="full">Linked obligation, control or task<input required value={form.entity} onChange={e => setForm({ ...form, entity: e.target.value })} /></label><label className="full">Verification note<textarea value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} /></label><div className="full form-actions"><button type="button" className="ghost" onClick={() => setEvidenceOpen(false)}>Cancel</button><button className="primary">Add to verification queue</button></div></form></Modal>}</>;
}
